"use client";

import React, { useEffect, useMemo } from "react";

interface LockedDocumentViewerProps {
  content: string;
}

// Helper: Convert numbers to Roman Numerals for Preliminary Pages
const toRoman = (num: number): string => {
  const lookup: { [key: string]: number } = { M: 1000, CM: 900, D: 500, CD: 400, C: 100, XC: 90, L: 50, XL: 40, X: 10, IX: 9, V: 5, IV: 4, I: 1 };
  let roman = '';
  for (let i in lookup) {
    while (num >= lookup[i]) {
      roman += i;
      num -= lookup[i];
    }
  }
  return roman.toLowerCase() || "i";
};

export default function LockedDocumentViewer({ content }: LockedDocumentViewerProps) {

  useEffect(() => {
    const handleContextMenu = (e: MouseEvent) => e.preventDefault();
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && ["p", "c", "a", "s"].includes(e.key.toLowerCase())) {
        e.preventDefault();
      }
    };
    document.addEventListener("contextmenu", handleContextMenu);
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("contextmenu", handleContextMenu);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  const formatInlineText = (text: string) => {
    if (!text.includes("**")) return text;
    const parts = text.split(/(\*\*.*?\*\*)/g);
    return parts.map((part, i) =>
      part.startsWith("**") && part.endsWith("**") ? (
        <strong key={i} className="font-bold">{part.slice(2, -2)}</strong>
      ) : part
    );
  };

  // --- THE NEW "MS WORD" PAGINATION ENGINE ---
  const { pages, toc, lot, chapterOneIndex } = useMemo(() => {
    if (!content) return { pages: [], toc: [], lot: [], chapterOneIndex: -1 };

    // 1. Clean the raw text and remove AI hallucinations
    let cleanText = content
      .replace(/^(#\s*)?(\*\*)?PRELIMINARY PAGES(\*\*)?\s*$/gim, '')
      .replace(/^(#\s*)?(\*\*)?APPENDICES(\*\*)?\s*$/gim, '');
    
    // Remove duplicate bold headers right above real headers
    cleanText = cleanText.replace(/^(#\s*)?(\*\*)?(CHAPTER [A-Z]+:.*?|CHAPTER \d+:.*?)(\*\*)?\s*\n+(?=(#\s*)?(\*\*)?(CHAPTER [A-Z]+:.*?|CHAPTER \d+:.*?|1\.0\s+Introduction)(\*\*)?)/gim, '');
    cleanText = cleanText.replace(/^\*\*(CHAPTER .*?)\*\*\s*$/gim, '');

    // 2. Parse the document into unbreakable blocks (Paragraphs, Tables, Headings)
    const rawBlocks = cleanText.split(/\n\n+/);
    const parsedBlocks: any[] = [];
    
    rawBlocks.forEach((blockText) => {
        blockText = blockText.trim();
        if (!blockText || blockText.match(/^[-*]{3,}$/)) return;

        // Explicit Page Breaks generated by your AI
        if (blockText.includes("[PAGE BREAK]")) {
             parsedBlocks.push({ type: 'explicit-break' });
             return;
        }

        // Table Detection (Highly accurate)
        if (blockText.includes('|') && blockText.includes('\n') && /^[|\-\s:]+$/m.test(blockText)) {
             const lines = blockText.split('\n');
             const tableStart = lines.findIndex(l => l.trim().startsWith('|'));
             if (tableStart > 0) {
                 parsedBlocks.push({ type: 'p', text: lines.slice(0, tableStart).join('\n') });
             }
             parsedBlocks.push({ type: 'table', text: lines.slice(tableStart).join('\n') });
             return;
        }

        // Standard Headings
        if (blockText.startsWith("# ")) {
             parsedBlocks.push({ type: 'h1', text: blockText.replace(/^#\s*/, '') });
        } else if (blockText.startsWith("## ")) {
             parsedBlocks.push({ type: 'h2', text: blockText.replace(/^##\s*/, '') });
        } else if (blockText.startsWith("### ")) {
             parsedBlocks.push({ type: 'h3', text: blockText.replace(/^###\s*/, '') });
        } else {
             parsedBlocks.push({ type: 'p', text: blockText });
        }
    });

    // 3. Mathematical Pagination (Calculates space so it NEVER cuts off text)
    const finalPages: any[][] = [];
    let currentPage: any[] = [];
    let currentLines = 0;
    const MAX_LINES_PER_PAGE = 38; // The physical capacity of an A4 page
    
    const generatedToc: any[] = [];
    const generatedLot: any[] = [];
    let chapOneIdx = -1;
    let tableCounter = 1;

    const pushPage = () => {
         if (currentPage.length > 0) {
              finalPages.push(currentPage);
              currentPage = [];
              currentLines = 0;
         }
    };

    parsedBlocks.forEach((block, index) => {
        if (block.type === 'explicit-break') {
            pushPage();
            return;
        }

        let blockLines = 0;
        let forceNewPage = false;

        // Estimate how much vertical space this block takes
        if (block.type === 'h1') {
             blockLines = 4;
             forceNewPage = true; // Every major heading (Chapter, Declaration) starts a new page!
             
             const titleClean = block.text.replace(/\*\*/g, '').trim();
             generatedToc.push({ title: titleClean, level: 1, globalPageIndex: finalPages.length });
             if (titleClean.toUpperCase().includes("CHAPTER ONE") || titleClean.toUpperCase().includes("CHAPTER 1")) {
                 chapOneIdx = finalPages.length;
             }
        } 
        else if (block.type === 'h2') {
             blockLines = 3;
             generatedToc.push({ title: block.text.replace(/\*\*/g, '').trim(), level: 2, globalPageIndex: finalPages.length });
        } 
        else if (block.type === 'h3') {
             blockLines = 2;
        } 
        else if (block.type === 'p') {
             blockLines = Math.ceil(block.text.length / 90) + 1; // Approx lines based on characters
        } 
        else if (block.type === 'table') {
             blockLines = block.text.split('\n').length * 1.5 + 2; // Tables take up space
             
             // Extract title for List of Tables
             let lotTitle = `Table ${tableCounter}`;
             if (index > 0 && parsedBlocks[index - 1].type === 'p') {
                 const prevText = parsedBlocks[index - 1].text.replace(/\*\*/g, '').trim();
                 if (prevText.toLowerCase().includes('table')) {
                     lotTitle = prevText.length > 60 ? prevText.substring(0, 60) + '...' : prevText;
                 }
             }
             generatedLot.push({ title: lotTitle, globalPageIndex: finalPages.length });
             tableCounter++;
        }

        // Logic to prevent stranding a heading at the bottom of a page
        const isHeading = block.type === 'h2' || block.type === 'h3';
        const isTooCloseToBottom = currentLines + blockLines >= MAX_LINES_PER_PAGE - 4;

        if (forceNewPage && currentPage.length > 0) {
             pushPage();
        } else if (isHeading && isTooCloseToBottom) {
             pushPage(); // Push heading to next page instead of leaving it alone
        } else if (currentLines + blockLines > MAX_LINES_PER_PAGE && currentPage.length > 0) {
             pushPage(); // Page is full, start a new one!
        }

        currentPage.push(block);
        currentLines += blockLines;
    });
    
    pushPage(); // Catch the last page

    return { pages: finalPages, toc: generatedToc, lot: generatedLot, chapterOneIndex: chapOneIdx };
  }, [content]);

  // --- Helper: Get Display Page Number ---
  const getDisplayPageNum = (globalIndex: number) => {
    if (globalIndex === 0) return "";
    if (chapterOneIndex !== -1 && globalIndex < chapterOneIndex) {
      return toRoman(globalIndex);
    }
    return (globalIndex - (chapterOneIndex !== -1 ? chapterOneIndex : 1) + 1).toString();
  };

  // --- DYNAMIC TOC RENDERER (MASSIVELY REDUCED TEXT SIZE) ---
  const renderDynamicToC = () => {
    return (
      <div className="w-full mt-4 mb-4 px-4 md:px-12 font-sans">
         <h1 className="text-lg md:text-xl font-black mt-0 mb-6 uppercase tracking-widest text-center">TABLE OF CONTENTS</h1>
        {toc.map((item, idx) => {
          if (item.globalPageIndex === 0) return null; 
          return (
            <div key={`toc-${idx}`} className={`flex w-full text-[10px] md:text-xs items-end mb-1 md:mb-2 ${item.level === 1 ? 'font-bold mt-3 md:mt-4' : 'pl-4 text-gray-800'}`}>
              <span className="bg-white pr-1 whitespace-nowrap">{item.title}</span>
              <span className="flex-grow border-b-[2px] border-dotted border-gray-400 relative -top-1 mx-1"></span>
              <span className="bg-white pl-1 font-medium">{getDisplayPageNum(item.globalPageIndex)}</span>
            </div>
          );
        })}
        
        {lot.length > 0 && (
          <div className="mt-10 page-break-before">
            <h2 className="text-lg md:text-xl font-black mb-6 uppercase tracking-wider text-center">LIST OF TABLES</h2>
            {lot.map((item, idx) => (
              <div key={`lot-${idx}`} className="flex w-full text-[10px] md:text-xs items-end mb-1 md:mb-2 pl-4 text-gray-800">
                <span className="bg-white pr-1 whitespace-nowrap">{item.title}</span>
                <span className="flex-grow border-b-[2px] border-dotted border-gray-400 relative -top-1 mx-1"></span>
                <span className="bg-white pl-1 font-medium">{getDisplayPageNum(item.globalPageIndex)}</span>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  // --- HTML TABLE GENERATOR ---
  const renderTable = (rawMarkdown: string, keyIndex: number) => {
    const rows = rawMarkdown.split('\n');
    const isSeparator = (r: string) => /^[|\-\s:]+$/.test(r.trim()) && r.includes('-');
    const cleanRows = rows.filter((r) => !isSeparator(r) && r.trim().length > 0);
    const hasHeader = rows.length > 1 && rows.some(isSeparator);

    const parseCells = (row: string) => {
      let cells = row.split('|').map(c => c.trim());
      if (cells.length > 0 && cells[0] === '') cells.shift();
      if (cells.length > 0 && cells[cells.length - 1] === '') cells.pop();
      return cells;
    };

    return (
      <div key={keyIndex} className="w-full overflow-x-auto my-6">
        <table className="w-full border-collapse border border-gray-400 text-[10px] md:text-xs text-left font-sans">
          {hasHeader && cleanRows.length > 0 && (
            <thead className="bg-gray-100">
              <tr>
                {parseCells(cleanRows[0]).map((cell, i) => (
                    <th key={i} className="py-2 px-3 border border-gray-400 font-bold text-gray-900">{formatInlineText(cell)}</th>
                ))}
              </tr>
            </thead>
          )}
          <tbody>
            {cleanRows.slice(hasHeader ? 1 : 0).map((row, rIdx) => {
              return (
                <tr key={rIdx} className="border-b border-gray-300 hover:bg-gray-50">
                  {parseCells(row).map((cell, cIdx) => (
                    <td key={cIdx} className="py-2 px-3 border border-gray-400 text-gray-800">{formatInlineText(cell)}</td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    );
  };

  if (!content) {
    return <div className="p-10 text-center text-gray-500 font-mono">Select a chapter to load the preview...</div>;
  }

  // Generate the final array of pages (inserting the ToC as Page 2 automatically)
  const finalRenderPages = [...pages];
  if (finalRenderPages.length > 1) {
      finalRenderPages.splice(1, 0, [{ type: 'auto-toc' }]);
  }

  return (
    <div className="bg-gray-200 py-6 md:py-10 px-2 md:px-10 overflow-y-auto locked-document-viewer select-none flex flex-col gap-8 md:gap-10 items-center min-h-[80vh]">
      {finalRenderPages.map((pageBlocks, index) => {
        const isCoverPage = index === 0;

        return (
          // 🚨 OVERFLOW-VISIBLE ensures no text is ever completely chopped off visually
          <div key={index} className="relative bg-white shadow-xl w-full max-w-[210mm] min-h-[297mm] px-8 py-12 md:px-[25.4mm] md:py-[25.4mm] pointer-events-none flex flex-col overflow-visible">
            
            <div className="absolute inset-0 pointer-events-none opacity-[0.04] flex items-center justify-center text-center z-0"
              style={{ backgroundImage: 'url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'400\'><text x=\'50%\' y=\'50%\' font-family=\'sans-serif\' font-size=\'36\' font-weight=\'900\' fill=\'%23d97706\' text-anchor=\'middle\' transform=\'rotate(-45 200 200)\'>ETOMU.com</text></svg>")', backgroundRepeat: 'repeat' }}>
            </div>

            <div className={`relative z-10 font-serif text-gray-900 flex-grow ${isCoverPage ? 'flex flex-col justify-center items-center text-center space-y-8' : 'text-justify'}`}>
              
              {pageBlocks.map((block: any, bIdx: number) => {
                if (block.type === 'auto-toc') return <div key={bIdx} className="w-full">{renderDynamicToC()}</div>;
                if (block.type === 'table') return renderTable(block.text, bIdx);
                
                if (block.type === 'h1') return <h1 key={bIdx} className="text-xl md:text-2xl font-black mt-0 mb-6 uppercase tracking-widest text-center">{formatInlineText(block.text)}</h1>;
                if (block.type === 'h2') return <h2 key={bIdx} className={`text-lg md:text-xl font-bold mt-8 mb-4 ${isCoverPage ? 'text-center' : 'text-left'}`}>{formatInlineText(block.text)}</h2>;
                if (block.type === 'h3') return <h3 key={bIdx} className={`text-base md:text-lg font-bold mt-6 mb-2 ${isCoverPage ? 'text-center' : 'text-left'}`}>{formatInlineText(block.text)}</h3>;

                return <p key={bIdx} className={`mb-4 text-sm md:text-[16px] leading-[2] ${isCoverPage ? 'text-center font-bold text-lg max-w-[80%]' : 'text-justify'}`}>{formatInlineText(block.text)}</p>;
              })}

            </div>

            {!isCoverPage && pageBlocks[0]?.type !== 'auto-toc' && (
              <div className="absolute bottom-[10mm] left-0 w-full text-center text-xs md:text-sm text-gray-500 font-serif">
                {getDisplayPageNum(index > 1 ? index - 1 : index)} 
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
