import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Etomu",
  description: "Read the Terms of Service for using the Etomu academic research workspace.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50 pb-20 font-sans">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 pt-20 pb-16 px-4 sm:px-8">
        <div className="max-w-3xl mx-auto animate-in slide-in-from-bottom-4 fade-in duration-700">
          <h1 className="text-3xl sm:text-5xl font-black text-gray-900 tracking-tighter mb-4">
            Terms of Service
          </h1>
          <p className="text-gray-500 font-medium leading-relaxed">
            By accessing or using Etomu, you agree to be bound by these terms. Please read them carefully.
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 sm:px-8 mt-12 space-y-12 animate-in fade-in duration-700 delay-100">
        
        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-4 border-b border-gray-200 pb-2">1. Academic Integrity</h2>
          <p className="text-gray-600 leading-relaxed mb-4">
            Etomu is designed to be an assistive workspace for formatting, topic generation, and structural guidance. It is <strong className="text-gray-900">not</strong> a replacement for original academic thought.
          </p>
          <ul className="list-disc pl-5 space-y-3 text-gray-600 leading-relaxed">
            <li>You are solely responsible for ensuring that your final submissions adhere to your institution's academic integrity and plagiarism policies.</li>
            <li>We do not guarantee that AI-generated text will pass all institutional AI detectors, though our tools are designed to humanize and assist in writing.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-4 border-b border-gray-200 pb-2">2. Payments and Credits</h2>
          <p className="text-gray-600 leading-relaxed mb-4">
            Certain features, such as full document downloads and bulk originality remediation, require payment via Mobile Money (UGX).
          </p>
          <ul className="list-disc pl-5 space-y-3 text-gray-600 leading-relaxed">
            <li><strong className="text-gray-800">No Refunds:</strong> Due to the digital nature of AI generation and the instant expenditure of API compute resources, all payments are final and non-refundable once a generation or download process has started.</li>
            <li>Prices are clearly displayed before any transaction is initiated.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-4 border-b border-gray-200 pb-2">3. Intellectual Property</h2>
          <p className="text-gray-600 leading-relaxed">
            You retain full ownership of all original data, documents, and concepts you input into Etomu. Etomu claims no ownership over your academic research or the specific outputs generated within your private workspace. The Etomu platform, its code, and its branding remain the intellectual property of Etomu.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-4 border-b border-gray-200 pb-2">4. Limitation of Liability</h2>
          <p className="text-gray-600 leading-relaxed">
            Etomu is provided "as is." We are not liable for any academic penalties, lost grades, or institutional actions taken against you resulting from the use of our software. It is your responsibility to review, edit, and verify all content generated by the workspace before academic submission.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-4 border-b border-gray-200 pb-2">5. Account Termination</h2>
          <p className="text-gray-600 leading-relaxed">
            We reserve the right to suspend or terminate accounts that abuse our systems, attempt to bypass payment gateways, or violate these terms of service without prior notice.
          </p>
        </section>

      </div>
    </main>
  );
}
